export const RoutesUtil = {
  getStarted: "/",
  jobView: "/applicant/jobs/screening/",
  screening: `/applicant/jobs/screening/${location.pathname.split("/")[4]}/interview`,
  completedInterview: `/applicant/jobs/screening/${location.pathname.split("/")[4]}/completedInterview`,
  baseUsers: "/users/dashboard",
  baseApplicant: "/applicant/dashboard",
};

export const AuthApiRoutes = {
  SignUp: "auth/signup",
  SignUpSSO: "auth/signupSSO",
  Login: "auth/login",
  LoginSSO: "auth/loginSSO",
  UpdateUserData: "auth/user",
  ToggleStatus: "auth/user/toggle-status",
  GetCompanyData: "auth/company-details",
  UpdateCompanyData: "auth/client",
  UploadProfileImage: "auth/upload/profile-pic",
  UploadLogo: "auth/upload/logo",
  VerifyEmail: "auth/verify-email",
  ResetPassword: "auth/reset-password",
  ChangePassword: "auth/change-password",
  InviteUser: "auth/invite-user",
  DeleteProfileImage: "auth/remove/profile-pic",
  DeleteLogo: "auth/remove/logo",
  LogOutUser: "auth/logout",
  ForgotPassword: "auth/send-reset-password-link",
  SendInviteEmail: "auth/send-invite-user-link",
  GetPlansDetails: "stripe/get-plans",
  CreatePaymentIntent: "stripe/create-payment-intent",
  PaymentWebhook: "stripe/payment-webhook",
  GetActivePlanDetails: "stripe/active-plan-details",
  GetCompanyLimit: "stripe/sendBroadcastLimit",
  CancelSubscription: "stripe/cancel-subscription",
  CreatePaymentLink: "stripe/create-payment-link",
  CreateCheckoutSession: "stripe/create-checkout-session",
  CreateCustomerPortalSession: "stripe/create-customer-portal-session",
};

export const JobsApiRoutes = {
  PublishJob: "jobs/create-job",
  GenerateJD: "jobs/job-description",
  DownloadCSV: "jobs/download/csv-jobs-template",
  UploadCSV: "jobs/upload/csv-jobs",
  ChangeStatus: "jobs/job/status",
  GetJobDetails: `jobs/job/`,
  GetApplicantDetails: `jobs/application/`,
  UpdateApplicantDetails: `jobs/application`,
  UploadResume: "jobs/upload/resume",
  sendInvite: "jobs/interview/send-invite",
  UpdateJobStatus: "jobs/job/status",
  CancelInviteStatus: "jobs/interview/cancel-invite",
  DashboardStats: "jobs/dashboard-stats",
  UpdateJob: "jobs/job",
  GetQuestionDetails: "jobs/question",
  AddQuestion: "jobs/question",
  UpdateQuestionDetails: "jobs/question",
  DeleteQuestion: "jobs/question",
  UpdateApplicationStatus: "jobs/application-status",
  bulkSendInvite: "jobs/interview/send-bulk-invite",
  downloadAiAssesment: "jobs/assessment",
  downloadResume: "jobs/download/resume",
  InterviewReport: `jobs/assessment/`,
  GetAllApplications: `jobs/applications`,
  GetQuestionBank: "jobs/question-bank",
  AddQuestionQB: "jobs/question-bank",
  UpdateQuestionDetailsQB: "jobs/question-bank",
  DeleteQuestionQB: "jobs/question-bank",
  AddCategoryQB: "jobs/question-category",
  UpdateCategoryQB: "jobs/question-category",
  DeleteCategoryQB: "jobs/question-category",
  GetAssessmentConfig: "jobs/ai-screening-settings",
  UpdateAssessmentConfig: "jobs/ai-screening-settings",
};

export const InverviewApiRoutes = {
  getJobDetails: `interview/`,
  GetApplicantDetails: `interview/`,
  GetQuestions: `interview/questions/`,
  SaveAudio: `interview/question/save-audio`,
  SaveVideo: `interview/question/save-video`,
  InterviewComplete: "interview/complete",
  startInterview: "interview/startInterview",
  InterviewReport: "",
};

export const AnalyticsApiRoutes = {
  DashboardAnalytics: "analytics/dashboard-analytics",
};
